### PR TITLE
My first doc changes

### PR DESCRIPTION
**Pull request by DigitalMonkeyPa1**
Please check for correctness.
Added a few images, hope you like it.
I didn't go much into the current terrain creation process, as it might be changed soon.
I will soon cover tools and settings.

### CODE REVIEW

**Comment by Zylann** [comment]
Your PR contains way too many files, it looks like you synced to the wrong commit of this repo

**Comment by DigitalMonkeyPa1** [comment]
Is it ok now, I think it still does not have any new doc changes, as I reverted new changes, can I merge my master with the new doc branch again and give another PR.

**Comment by Zylann** [comment]
You can either rebase or make another PR

**Comment by DigitalMonkeyPa1** [comment]
I am a super idiot (noob), so I just deleted my fork repository and then re-fork it, so I close this PR.

Sorry, I was only using GitHub website only, I tried to sync from the website, as you saw it messed up.
So I installed Git bash today, tried with that, but again something is not fine, so I deleted GitHub repo.

**Comment by DigitalMonkeyPa1** [comment]
I think it works, I mean an easy way to sync fork with base repo is to delete fork and then re-fork it.
Why GitHub does not have a "Sync" or "Synchronize" button?

**Comment by DigitalMonkeyPa1** [comment]
At last, git said everything is up-to-date.
Last time I made changes in GitHub website, so this time can I make changes in my local repository and then push them via git commands?
Can I create another branch for docs?

Or better can I just edit that main.md file and put it in a zip file containing that file and other files like pictures and then upload it here in these comments, so that you can copy and paste the required changes yourself?

I just downloaded git book, so I think within a week or two I will get comfortable with that.

**Comment by Zylann** [comment]
Usually the flow is:
- You clone the repo on Github
- Get it locally
- Do your changes
- Push them to your clone
- Then Github will propose you to do the PR

**Pull request closed without merging**
